"""
LlamaCpp Nodes Package
"""

from .adv_prompt import NODE_CLASS_MAPPINGS as ADV_PROMPT_MAPPINGS
from .adv_prompt import NODE_DISPLAY_NAME_MAPPINGS as ADV_PROMPT_DISPLAY_MAPPINGS
from .advpp_prompt import NODE_CLASS_MAPPINGS as ADVPP_PROMPT_MAPPINGS
from .advpp_prompt import NODE_DISPLAY_NAME_MAPPINGS as ADVPP_PROMPT_DISPLAY_MAPPINGS
from .basic_prompt import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS
from .basic_prompt import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_MAPPINGS
from .connection import NODE_CLASS_MAPPINGS as CONNECTION_MAPPINGS
from .connection import NODE_DISPLAY_NAME_MAPPINGS as CONNECTION_DISPLAY_MAPPINGS
from .generate import NODE_CLASS_MAPPINGS as GENERATE_MAPPINGS
from .generate import NODE_DISPLAY_NAME_MAPPINGS as GENERATE_DISPLAY_MAPPINGS
from .model_info import NODE_CLASS_MAPPINGS as MODEL_INFO_MAPPINGS
from .model_info import NODE_DISPLAY_NAME_MAPPINGS as MODEL_INFO_DISPLAY_MAPPINGS
from .model_management import NODE_CLASS_MAPPINGS as MODEL_MAPPINGS
from .model_management import NODE_DISPLAY_NAME_MAPPINGS as MODEL_DISPLAY_MAPPINGS
from .prompt_output import NODE_CLASS_MAPPINGS as OUTPUT_MAPPINGS
from .prompt_output import NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_DISPLAY_MAPPINGS
from .start_router import NODE_CLASS_MAPPINGS as ROUTER_MAPPINGS
from .start_router import NODE_DISPLAY_NAME_MAPPINGS as ROUTER_DISPLAY_MAPPINGS
from .start_server import NODE_CLASS_MAPPINGS as START_MAPPINGS
from .start_server import NODE_DISPLAY_NAME_MAPPINGS as START_DISPLAY_MAPPINGS
from .stop_server import NODE_CLASS_MAPPINGS as STOP_MAPPINGS
from .stop_server import NODE_DISPLAY_NAME_MAPPINGS as STOP_DISPLAY_MAPPINGS
from .structured_output import NODE_CLASS_MAPPINGS as STRUCTURED_OUTPUT_MAPPINGS
from .structured_output import NODE_DISPLAY_NAME_MAPPINGS as STRUCTURED_OUTPUT_DISPLAY_MAPPINGS
from .task_profile import NODE_CLASS_MAPPINGS as TASK_PROFILE_MAPPINGS
from .task_profile import NODE_DISPLAY_NAME_MAPPINGS as TASK_PROFILE_DISPLAY_MAPPINGS
from .token_ban import NODE_CLASS_MAPPINGS as TOKEN_BAN_MAPPINGS
from .token_ban import NODE_DISPLAY_NAME_MAPPINGS as TOKEN_BAN_DISPLAY_MAPPINGS
from .token_count import NODE_CLASS_MAPPINGS as TOKEN_COUNT_MAPPINGS
from .token_count import NODE_DISPLAY_NAME_MAPPINGS as TOKEN_COUNT_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **START_MAPPINGS,
    **STOP_MAPPINGS,
    **PROMPT_MAPPINGS,
    **ROUTER_MAPPINGS,
    **MODEL_MAPPINGS,
    **OUTPUT_MAPPINGS,
    **ADV_PROMPT_MAPPINGS,
    **ADVPP_PROMPT_MAPPINGS,
    **TOKEN_BAN_MAPPINGS,
    **CONNECTION_MAPPINGS,
    **TOKEN_COUNT_MAPPINGS,
    **MODEL_INFO_MAPPINGS,
    **STRUCTURED_OUTPUT_MAPPINGS,
    **GENERATE_MAPPINGS,
    **TASK_PROFILE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **START_DISPLAY_MAPPINGS,
    **STOP_DISPLAY_MAPPINGS,
    **PROMPT_DISPLAY_MAPPINGS,
    **ROUTER_DISPLAY_MAPPINGS,
    **MODEL_DISPLAY_MAPPINGS,
    **OUTPUT_DISPLAY_MAPPINGS,
    **ADV_PROMPT_DISPLAY_MAPPINGS,
    **ADVPP_PROMPT_DISPLAY_MAPPINGS,
    **TOKEN_BAN_DISPLAY_MAPPINGS,
    **CONNECTION_DISPLAY_MAPPINGS,
    **TOKEN_COUNT_DISPLAY_MAPPINGS,
    **MODEL_INFO_DISPLAY_MAPPINGS,
    **STRUCTURED_OUTPUT_DISPLAY_MAPPINGS,
    **GENERATE_DISPLAY_MAPPINGS,
    **TASK_PROFILE_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
