"""
LlamaCpp Nodes Package
"""

from .start_server import NODE_CLASS_MAPPINGS as START_MAPPINGS
from .start_server import NODE_DISPLAY_NAME_MAPPINGS as START_DISPLAY_MAPPINGS
from .stop_server import NODE_CLASS_MAPPINGS as STOP_MAPPINGS
from .stop_server import NODE_DISPLAY_NAME_MAPPINGS as STOP_DISPLAY_MAPPINGS
from .basic_prompt import NODE_CLASS_MAPPINGS as PROMPT_MAPPINGS
from .basic_prompt import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **START_MAPPINGS,
    **STOP_MAPPINGS,
    **PROMPT_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **START_DISPLAY_MAPPINGS,
    **STOP_DISPLAY_MAPPINGS,
    **PROMPT_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
